# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKeyPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.IntegerField(verbose_name='keyID')),
                ('v_code', models.CharField(max_length=32, verbose_name='vCode')),
            ],
        ),
    ]
